CREATE TABLE `users` (
 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 `email` VARCHAR(255) NOT NULL,
 `first_name` VARCHAR(255) NOT NULL,
 `last_name` VARCHAR(255) NOT NULL,
 `password` VARCHAR(255) NOT NULL,
 `balance` BIGINT UNSIGNED NOT NULL DEFAULT 0,
 `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 primary key (`id`)
);

